version:  0.1

phases:
  install:
    commands:
      # Install Serverless Framework
      - npm install -g serverless 2>&1 >/dev/null
  build:
    commands:
      # NOTE: Should exactly match the name of your app (not security!) repository, and use a delimiter of '.' not '-'
      # For example, gs.svc.avatar.security would be 'gs.svc.avatar'
      - sls deploy --serviceName gs.svc.template
  post_build:
    commands:
      # Remove pipelines
      # USE WITH EXTREME CAUTION!
      # Read and understand https://gamestop.atlassian.net/wiki/x/R4CAAw before proceeding:
      #- sls remove --stage $STAGE --serviceName my.new.service --region us-east-1
