version:  0.1

phases:
  install:
    commands:
    
  build:
    commands:
      # Deploy Security
      - serverless deploy
  post_build:
    commands:
      # Remove pipelines
      # USE WITH EXTREME CAUTION!
      # Read and understand https://gamestop.atlassian.net/wiki/x/R4CAAw before proceeding:
      #- serverless remove
